// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVxdZmsz67Q-ZjhPsdVrE9N-O_d63wTQw',
    appId: '1:149833327235:web:7ebf058a3422b5ea4f71b6',
    messagingSenderId: '149833327235',
    projectId: 'sherpa-22244',
    authDomain: 'sherpa-22244.firebaseapp.com',
    storageBucket: 'sherpa-22244.firebasestorage.app',
    measurementId: 'G-15TDXHR62B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYCIGe8W9INZ5Lv2OuHTukHTYmF3udTd4',
    appId: '1:149833327235:android:b823725e36443d454f71b6',
    messagingSenderId: '149833327235',
    projectId: 'sherpa-22244',
    storageBucket: 'sherpa-22244.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHPAZiPZQAzVKLvFgtWPji8DLa8PRD-Uo',
    appId: '1:149833327235:ios:21d7735222907b184f71b6',
    messagingSenderId: '149833327235',
    projectId: 'sherpa-22244',
    storageBucket: 'sherpa-22244.firebasestorage.app',
    iosBundleId: 'com.example.miceActiveg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHPAZiPZQAzVKLvFgtWPji8DLa8PRD-Uo',
    appId: '1:149833327235:ios:21d7735222907b184f71b6',
    messagingSenderId: '149833327235',
    projectId: 'sherpa-22244',
    storageBucket: 'sherpa-22244.firebasestorage.app',
    iosBundleId: 'com.example.miceActiveg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVxdZmsz67Q-ZjhPsdVrE9N-O_d63wTQw',
    appId: '1:149833327235:web:a63a0e0651583bc74f71b6',
    messagingSenderId: '149833327235',
    projectId: 'sherpa-22244',
    authDomain: 'sherpa-22244.firebaseapp.com',
    storageBucket: 'sherpa-22244.firebasestorage.app',
    measurementId: 'G-55KRQHQTE8',
  );

}